### ISSUE TITLE
Прошу доработать.

### ISSUE THREAD

**Issue by Ford2008a** [timaaos/YandexGamesTurboWarp#1]
1. При включенной рекламе за вознаграждение и переходе на соседнюю вкладку и обратно звук включается даже если реклама не закончилась.
2. При включении полноэкранной рекламы звук не выключается. Или делается попытка выключения звука но остаётся включенным.

**Comment by timaaos** [comment]
Скорее всего смогу выкатить фикс уже сегодня. Спасибо за поиск багов!

**Comment by timaaos** [comment]
Исправлено коммитом https://github.com/timaaos/YandexGamesTurboWarp/commit/1edbfaa71109157d37af8803e3285ee05b1c3fdb
